# Generated by Django 5.0.7 on 2026-08-23 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('audience', models.CharField(choices=[('ALL', 'Everyone'), ('STUDENTS', 'Students only'), ('FACULTY', 'Faculty only'), ('PARENTS', 'Parents only')], default='ALL', max_length=10)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='notices/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_urgent', models.BooleanField(default=False)),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices_posted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['audience', '-created_at'], name='notices_not_audienc_c3738e_idx')],
            },
        ),
    ]
