# Generated by Django 5.0.7 on 2026-08-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='audience',
            field=models.CharField(choices=[('ALL', 'Everyone'), ('STUDENTS', 'Students only'), ('FACULTY', 'Faculty only'), ('STAFF', 'All staff (teaching & non-teaching)'), ('PARENTS', 'Parents only')], default='ALL', max_length=10),
        ),
    ]
