# Generated by Django 5.0.7 on 2026-08-23 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('faculty', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('exam_type', models.CharField(choices=[('MIDTERM', 'Midterm'), ('FINAL', 'Final'), ('QUIZ', 'Quiz'), ('ASSIGNMENT', 'Assignment')], default='MIDTERM', max_length=20)),
                ('date', models.DateField()),
                ('max_marks', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
                ('weightage_percent', models.DecimalField(decimal_places=2, default=100, help_text='Contribution of this exam to final grade', max_digits=5)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academics.course')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=6)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('graded_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='exams.exam')),
                ('graded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades_given', to='faculty.facultyprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='students.studentprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'exam'], name='exams_grade_student_fa9ee5_idx')],
                'unique_together': {('exam', 'student')},
            },
        ),
    ]
