# Generated by Django 5.0.7 on 2026-08-25 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['-graded_at']},
        ),
    ]
