# Generated by Django 5.0.7 on 2026-08-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('DEPT_ADMIN', 'Department Admin'), ('HOD', 'Head of Department'), ('ADVISOR', 'Advisor / Mentor'), ('FACULTY', 'Faculty'), ('NON_TEACHING', 'Non-Teaching Staff'), ('STUDENT', 'Student'), ('PARENT', 'Parent')], default='STUDENT', max_length=20),
        ),
    ]
