# Generated by Django 5.0.7 on 2026-08-23 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('faculty', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['code']},
        ),
        migrations.AddField(
            model_name='department',
            name='dept_admin',
            field=models.ForeignKey(blank=True, help_text="Account with the Department Admin role that manages this department's records.", limit_choices_to={'role': 'DEPT_ADMIN'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_departments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='head_of_department',
            field=models.ForeignKey(blank=True, help_text='Must be a staff member whose account role is Head of Department.', limit_choices_to={'user__role': 'HOD'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_department', to='faculty.facultyprofile'),
        ),
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('material_type', models.CharField(choices=[('SYLLABUS', 'Syllabus'), ('NOTES', 'Notes'), ('ASSIGNMENT', 'Assignment'), ('VIDEO', 'Video link'), ('OTHER', 'Other')], default='NOTES', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='course_materials/')),
                ('external_link', models.URLField(blank=True)),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='academics.course')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_materials', to='faculty.facultyprofile')),
            ],
            options={
                'ordering': ['-uploaded_on'],
            },
        ),
    ]
