# Generated by Django 5.0.7 on 2026-08-23 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BonafideRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(help_text='e.g. Bank loan, passport application, bus pass', max_length=200)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('requested_on', models.DateTimeField(auto_now_add=True)),
                ('processed_on', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.CharField(blank=True, max_length=300)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_bonafides', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonafide_requests', to='students.studentprofile')),
            ],
            options={
                'ordering': ['-requested_on'],
            },
        ),
        migrations.CreateModel(
            name='AdvisorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.PositiveSmallIntegerField()),
                ('remarks', models.TextField(blank=True)),
                ('assigned_on', models.DateField(auto_now_add=True)),
                ('advisor', models.ForeignKey(limit_choices_to={'user__role': 'ADVISOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='advisees', to='faculty.facultyprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisor_assignments', to='students.studentprofile')),
            ],
            options={
                'ordering': ['-academic_year'],
                'unique_together': {('student', 'academic_year')},
            },
        ),
    ]
