# Generated by Django 5.0.7 on 2026-08-23 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveSmallIntegerField()),
                ('academic_year', models.CharField(help_text='e.g. 2026-2027', max_length=9)),
                ('tuition_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hostel_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('other_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='academics.department')),
            ],
            options={
                'unique_together': {('department', 'semester', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=10)),
                ('gateway_order_id', models.CharField(blank=True, max_length=100)),
                ('gateway_payment_id', models.CharField(blank=True, max_length=100)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_payments', to='students.studentprofile')),
                ('fee_structure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='fees.feestructure')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'status'], name='fees_feepay_student_99fef1_idx')],
            },
        ),
    ]
