# Generated by Django 5.0.7 on 2026-08-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feepayment',
            name='gateway_order_id',
        ),
        migrations.RemoveField(
            model_name='feepayment',
            name='gateway_payment_id',
        ),
        migrations.AddField(
            model_name='feepayment',
            name='remarks',
            field=models.CharField(blank=True, help_text='e.g. receipt number, mode of payment', max_length=255),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='SUCCESS', max_length=10),
        ),
    ]
